/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6p2_dessireochoa_22111211;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author dessi
 */
public class PokemonFight extends javax.swing.JFrame {

    /**
     * Creates new form PokemonFight
     */
    public PokemonFight() {
        initComponents();

        usuarios.add(new Usuarios("Luis", "Barrieri", "Luismi", "1234", new Date(), Color.CYAN));
        usuarios.get(0).addPokedex();
        ((Pokedex) usuarios.get(0).get1Pokedex(0)).addPokemonE("Jotaro", 15, "Media", 20);
        ((Pokedex) usuarios.get(0).get1Pokedex(0)).addPokemonV("Dio", 12, "Alta", 23);
        usuarios.add(new Usuarios("Isis", "Lopez", "Holi", "jijiji", new Date(), Color.MAGENTA));
        usuarios.get(1).addPokedex();
        ((Pokedex) usuarios.get(1).get1Pokedex(0)).addPokemonP("Sakura", 10, "Baja", 15);
        ((Pokedex) usuarios.get(1).get1Pokedex(0)).addPokemonF("Sailor", 15, "Alta", 12);
        pokegrupos.add(new PokeGrupos("Lolnoc", new Date(), usuarios.get(0), "Novato"));
        pokegrupos.get(0).addMiembro(usuarios.get(0));
        pokegrupos.get(0).addMiembro(usuarios.get(1));
        DefaultComboBoxModel modelo
                = (DefaultComboBoxModel) jComboBox1_Pokegrupos2.getModel();
        for (PokeGrupos p : pokegrupos) {
            modelo.addElement(p.getNombre());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog2_Registro = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1_registrame = new javax.swing.JButton();
        jButton2_Color = new javax.swing.JButton();
        jTextField1_Nombre = new javax.swing.JTextField();
        jTextField2_Usuario = new javax.swing.JTextField();
        jTextField3_Apellido = new javax.swing.JTextField();
        jTextField4_Contraseña = new javax.swing.JTextField();
        jDateChooser1_edad = new com.toedter.calendar.JDateChooser();
        jDialog1_Login = new javax.swing.JDialog();
        jLabel18 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1_usuario1 = new javax.swing.JTextField();
        jTextField2_contraseña1 = new javax.swing.JTextField();
        jButton1_ingresar1 = new javax.swing.JButton();
        jButton2_Registrarme1 = new javax.swing.JButton();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        Velocidad = new javax.swing.ButtonGroup();
        Tipo = new javax.swing.ButtonGroup();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jButton1_Salirse2 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jComboBox1_Pokegrupos2 = new javax.swing.JComboBox<>();
        jButton2_Unirme2 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jTextField1_CreaGrupo2 = new javax.swing.JTextField();
        jButton3_CrearGrupo2 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTree = new javax.swing.JTree();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField1_Nombre2 = new javax.swing.JTextField();
        jTextField2_Daño2 = new javax.swing.JTextField();
        jTextField3_Vida2 = new javax.swing.JTextField();
        jButton1_JTree2 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jButton2_Editar2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2_Logout = new javax.swing.JMenu();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Registro");

        jLabel5.setText("Nombre:");

        jLabel6.setText("Apellido:");

        jLabel7.setText("Fecha Nacimiento");

        jLabel8.setText("Usuario");

        jLabel9.setText("Color Favorito");

        jLabel10.setText("Contraseña:");

        jButton1_registrame.setText("Registrame");
        jButton1_registrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_registrameMouseClicked(evt);
            }
        });

        jButton2_Color.setBackground(new java.awt.Color(255, 255, 0));
        jButton2_Color.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2_ColorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jDialog2_RegistroLayout = new javax.swing.GroupLayout(jDialog2_Registro.getContentPane());
        jDialog2_Registro.getContentPane().setLayout(jDialog2_RegistroLayout);
        jDialog2_RegistroLayout.setHorizontalGroup(
            jDialog2_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2_RegistroLayout.createSequentialGroup()
                .addGroup(jDialog2_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog2_RegistroLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel2))
                    .addGroup(jDialog2_RegistroLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jDialog2_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialog2_RegistroLayout.createSequentialGroup()
                                .addGroup(jDialog2_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                                .addGroup(jDialog2_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)))
                            .addGroup(jDialog2_RegistroLayout.createSequentialGroup()
                                .addGroup(jDialog2_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jDateChooser1_edad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField1_Nombre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField3_Apellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(94, 94, 94))
            .addGroup(jDialog2_RegistroLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jButton1_registrame)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog2_RegistroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDialog2_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField2_Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(jTextField4_Contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(jButton2_Color, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        jDialog2_RegistroLayout.setVerticalGroup(
            jDialog2_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2_RegistroLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addGroup(jDialog2_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog2_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jDialog2_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog2_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jDialog2_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog2_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2_Color, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButton1_registrame)
                .addGap(38, 38, 38))
        );

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setText("Log In");

        jLabel3.setText("Usuario:");

        jLabel4.setText("Contraseña:");

        jTextField2_contraseña1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2_contraseña1ActionPerformed(evt);
            }
        });

        jButton1_ingresar1.setText("Ingresar");
        jButton1_ingresar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_ingresar1MouseClicked(evt);
            }
        });

        jButton2_Registrarme1.setText("Registrarme");
        jButton2_Registrarme1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_Registrarme1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1_LoginLayout = new javax.swing.GroupLayout(jDialog1_Login.getContentPane());
        jDialog1_Login.getContentPane().setLayout(jDialog1_LoginLayout);
        jDialog1_LoginLayout.setHorizontalGroup(
            jDialog1_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1_LoginLayout.createSequentialGroup()
                .addGroup(jDialog1_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1_LoginLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel18))
                    .addGroup(jDialog1_LoginLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jDialog1_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jTextField1_usuario1)
                            .addComponent(jTextField2_contraseña1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)))
                    .addGroup(jDialog1_LoginLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jButton1_ingresar1)
                        .addGap(71, 71, 71)
                        .addComponent(jButton2_Registrarme1)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jDialog1_LoginLayout.setVerticalGroup(
            jDialog1_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1_LoginLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel18)
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jTextField1_usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jTextField2_contraseña1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jDialog1_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_ingresar1)
                    .addComponent(jButton2_Registrarme1))
                .addGap(61, 61, 61))
        );

        jMenuItem1.setText("Mostrar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Editar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        jMenuItem3.setText("Eliminar");
        jPopupMenu1.add(jMenuItem3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PokeFight");

        jTabbedPane3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane3StateChanged(evt);
            }
        });

        jButton1_Salirse2.setText("Salirme de Pokegrupo");

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Unirme a un Pokegrupo");

        jButton2_Unirme2.setText("Unirme");
        jButton2_Unirme2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_Unirme2ActionPerformed(evt);
            }
        });

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Crear Pokegrupo");

        jTextField1_CreaGrupo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_CreaGrupo2ActionPerformed(evt);
            }
        });

        jButton3_CrearGrupo2.setText("Crear Grupo");

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane5.setViewportView(jTextArea3);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Lista de Usuarios de mi Pokegrupo");

        jButton1.setText("Ver");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jButton1_Salirse2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1_Pokegrupos2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(90, 90, 90)
                            .addComponent(jButton2_Unirme2))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jTextField1_CreaGrupo2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jButton3_CrearGrupo2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1_Salirse2)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(jButton1)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1_Pokegrupos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2_Unirme2)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1_CreaGrupo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3_CrearGrupo2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Pokegrupo", jPanel5);

        jTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTreeMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTree);

        jLabel22.setText("Nombre");

        jLabel23.setText("Daño");

        jLabel24.setText("Pts. Vida");

        jButton1_JTree2.setText("<");

        jLabel25.setText("Velocidad");

        Velocidad.add(jRadioButton15);
        jRadioButton15.setText("Baja");

        Velocidad.add(jRadioButton16);
        jRadioButton16.setText("Media");

        Velocidad.add(jRadioButton17);
        jRadioButton17.setText("Alta ");
        jRadioButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton17ActionPerformed(evt);
            }
        });

        jLabel26.setText("Tipo");

        Tipo.add(jRadioButton18);
        jRadioButton18.setText("Electrico");

        Tipo.add(jRadioButton19);
        jRadioButton19.setText("Psiquico");

        Tipo.add(jRadioButton20);
        jRadioButton20.setText("Venenoso");
        jRadioButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton20ActionPerformed(evt);
            }
        });

        Tipo.add(jRadioButton21);
        jRadioButton21.setText("Fantasma");

        jButton2_Editar2.setText("Editar");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton1_JTree2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1_Nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2_Daño2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(jButton2_Editar2))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jTextField3_Vida2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton16)
                            .addComponent(jRadioButton15)
                            .addComponent(jLabel25)
                            .addComponent(jRadioButton17))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jRadioButton18)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton21)
                                    .addComponent(jRadioButton20)
                                    .addComponent(jRadioButton19))))))
                .addGap(99, 99, 99))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1_Nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2_Daño2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3_Vida2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton15)
                                    .addComponent(jRadioButton18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton16)
                                    .addComponent(jRadioButton19)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jButton1_JTree2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton17)
                            .addComponent(jRadioButton20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton21)
                        .addGap(36, 36, 36)
                        .addComponent(jButton2_Editar2)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Pokemones", jPanel6);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Usuario:");

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jMenu1.setText("Login");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2_Logout.setText("LogOut");
        jMenu2_Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2_LogoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2_Logout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_ingresar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_ingresar1MouseClicked

        for (Usuarios U : usuarios) {
            if (jTextField1_usuario1.getText().equals(U.getNombreUsuario())
                    && jTextField2_contraseña1.getText().equals(U.getContraseña())) {
                jDialog1_Login.setVisible(false);
                JOptionPane.showMessageDialog(jMenu1, "Usuario encontrado");
                jTextField2.setText(U.getNombreUsuario());

            }
        }

    }//GEN-LAST:event_jButton1_ingresar1MouseClicked

    private void jTextField1_CreaGrupo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_CreaGrupo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_CreaGrupo2ActionPerformed

    private void jRadioButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton17ActionPerformed

    private void jRadioButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton20ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked

        jDialog1_Login.pack();
        jDialog1_Login.setLocationRelativeTo(this);
        jDialog1_Login.setModal(true);
        jDialog1_Login.setVisible(true);

    }//GEN-LAST:event_jMenu1MouseClicked

    private void jButton2_Unirme2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_Unirme2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2_Unirme2ActionPerformed

    private void jButton2_Registrarme1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_Registrarme1ActionPerformed
        jDialog1_Login.setVisible(false);
        jDialog2_Registro.pack();
        jDialog2_Registro.setLocationRelativeTo(this);
        jDialog2_Registro.setModal(true);
        jDialog2_Registro.setVisible(true);

    }//GEN-LAST:event_jButton2_Registrarme1ActionPerformed

    private void jTextField2_contraseña1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2_contraseña1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_contraseña1ActionPerformed

    private void jMenu2_LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2_LogoutMouseClicked

        jDialog1_Login.pack();
        jDialog1_Login.setLocationRelativeTo(this);
        jDialog1_Login.setModal(true);
        jDialog1_Login.setVisible(true);

    }//GEN-LAST:event_jMenu2_LogoutMouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2_ColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2_ColorMouseClicked
        jButton2_Color.setBackground(
                JColorChooser.showDialog(
                        jButton2_Registrarme1, "Seleccione un color",
                        Color.yellow)
        );
    }//GEN-LAST:event_jButton2_ColorMouseClicked

    private void jButton1_registrameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_registrameMouseClicked
        String nombre;
        String apellido;
        String nombreUsuario;
        String contraseña;
        Date edad;
        Color colorFavorito;

        nombre = jTextField1_Nombre.getText();
        apellido = jTextField3_Apellido.getText();
        nombreUsuario = jTextField2_Usuario.getText();
        contraseña = jTextField4_Contraseña.getText();
        colorFavorito = jButton2_Color.getBackground();
        edad = jDateChooser1_edad.getDate();
        
        usuarios.add(new Usuarios(nombre, apellido, nombreUsuario, contraseña, edad, colorFavorito));

        JOptionPane.showMessageDialog(jDialog2_Registro, "Usuario creado");
        jTextField2.setText(nombreUsuario);
        jDialog2_Registro.setVisible(false);
        
        


    }//GEN-LAST:event_jButton1_registrameMouseClicked

    private void jTabbedPane3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane3StateChanged
        DefaultTreeModel m = (DefaultTreeModel) jTree.getModel();

        DefaultMutableTreeNode raiz
                = (DefaultMutableTreeNode) m.getRoot();
        raiz.removeAllChildren();

        DefaultMutableTreeNode nodo_pokedex1;
        nodo_pokedex1
                = new DefaultMutableTreeNode(
                        new Pokedex() + " 1"
                );

        DefaultMutableTreeNode nodo_pokedex2;
        nodo_pokedex2
                = new DefaultMutableTreeNode(
                        new Pokedex() + " 2"
                );

        DefaultMutableTreeNode nodo_pokedex3;
        nodo_pokedex3
                = new DefaultMutableTreeNode(
                        new Pokedex() + " 3"
                );

        for (Usuarios u : usuarios) {
            if (jTextField2.getText().equals(u.getNombreUsuario())) {
                for (Pokedex px : u.getPokedex()) {
                    for (Pokemones pk : px.getPokemones()) {
                        DefaultMutableTreeNode pokemon;
                        pokemon
                                = new DefaultMutableTreeNode(
                                        pk
                                );
                        
                        nodo_pokedex1.add(pokemon);
                    }
                }
            }
        }

     
        raiz.add(nodo_pokedex1);
        raiz.add(nodo_pokedex2);
        raiz.add(nodo_pokedex3);
        m.reload();
    }//GEN-LAST:event_jTabbedPane3StateChanged

    private void jTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTreeMouseClicked
        if (evt.isMetaDown()) {
            //seleccionar un nodo con click derecho
            int row = jTree.getClosestRowForLocation(
                    evt.getX(), evt.getY());
            jTree.setSelectionRow(row);
            Object v1
                    = jTree.getSelectionPath().
                            getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            if (nodo_seleccionado.getUserObject() instanceof Pokemones) {
                Pokemones pokemonSeleccionado
                        = (Pokemones) nodo_seleccionado.
                                getUserObject();
                jPopupMenu1.show(evt.getComponent(),
                        evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jTreeMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       JOptionPane.showMessageDialog(this, ((Pokemones)nodo_seleccionado.getUserObject()).getNombre() + "\n Velocidad: "+
                                           ((Pokemones)nodo_seleccionado.getUserObject()).getVelocidad() + "\n Daño: "+
                                           ((Pokemones)nodo_seleccionado.getUserObject()).getDaño()+"\n Daño: "+
                                           ((Pokemones)nodo_seleccionado.getUserObject()).getVida());
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       JOptionPane.showMessageDialog(this, "Ingrese los nuevos cambios al lado izquierdo");
       String nombre = "";
       float daño = 0;
       String velocidad = ""; int vid = 0;
       
       nombre = jTextField1_Nombre2.getText();
       daño = Integer.parseInt(jTextField2_Daño2.getText());
       vid = Integer.parseInt(jTextField3_Vida2.getText());
       
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String usuario = jTextField2.getText();
        PokeGrupos pk;

        for (PokeGrupos p : pokegrupos) {
            for (Usuarios usu : p.getMiembros()) {
                if (usu.getNombreUsuario().equals(jTextField2.getText())) {
                    pk = p;
                    jTextArea3.setText("");
                    for (Usuarios u : pk.getMiembros()) {
                        jTextArea3.append(u.getNombreUsuario() + "\n");
                    }
                }
            }
        }


    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PokemonFight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PokemonFight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PokemonFight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PokemonFight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PokemonFight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Tipo;
    private javax.swing.ButtonGroup Velocidad;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1_JTree2;
    private javax.swing.JButton jButton1_Salirse2;
    private javax.swing.JButton jButton1_ingresar1;
    private javax.swing.JButton jButton1_registrame;
    private javax.swing.JButton jButton2_Color;
    private javax.swing.JButton jButton2_Editar2;
    private javax.swing.JButton jButton2_Registrarme1;
    private javax.swing.JButton jButton2_Unirme2;
    private javax.swing.JButton jButton3_CrearGrupo2;
    private javax.swing.JComboBox<String> jComboBox1_Pokegrupos2;
    private com.toedter.calendar.JDateChooser jDateChooser1_edad;
    private javax.swing.JDialog jDialog1_Login;
    private javax.swing.JDialog jDialog2_Registro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2_Logout;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1_CreaGrupo2;
    private javax.swing.JTextField jTextField1_Nombre;
    private javax.swing.JTextField jTextField1_Nombre2;
    private javax.swing.JTextField jTextField1_usuario1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField2_Daño2;
    private javax.swing.JTextField jTextField2_Usuario;
    private javax.swing.JTextField jTextField2_contraseña1;
    private javax.swing.JTextField jTextField3_Apellido;
    private javax.swing.JTextField jTextField3_Vida2;
    private javax.swing.JTextField jTextField4_Contraseña;
    private javax.swing.JTree jTree;
    // End of variables declaration//GEN-END:variables

    ArrayList<Usuarios> usuarios = new ArrayList();
    ArrayList<PokeGrupos> pokegrupos = new ArrayList();
    DefaultMutableTreeNode nodo_seleccionado;

}
